rule_sets:
  - tag: private-and-local
    type: inline
    match:
      - domain_suffix:
          - lan
          - local
      - ip_cidr:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
          - 127.0.0.0/8
      - ip6_cidr:
          - fc00::/7
          - fe80::/10
          - ::1/128

route_rules:
  - rule_set:
      - private-and-local
    action: bypass

status_tests:
  proxy:
    ipv4:
      - domain: ifconfig.io
        url: https://ifconfig.io
    ipv6:
      - domain: ifconfig.io
        url: https://ifconfig.io
  bypass:
    ipv4:
      - domain: ipinfo.io
        url: https://ipinfo.io/ip
    ipv6:
      - domain: v6.ipinfo.io
        url: https://v6.ipinfo.io/ip
  dns:
    ipv4:
      - www.google.com
      - ifconfig.io
      - openwrt.org
    ipv6:
      - www.google.com
      - ifconfig.io
      - openwrt.org

final_action: bypass
